### PR TITLE
feature-2 is developed please review

### PR DESCRIPTION
**Pull request by sivadevops1014**
feature-2 is developed please review

### CODE REVIEW

**Comment by sivadevops1014** [comment]
check once again

**Comment by sivadevops1014** [comment]
> check once again

yes, checked once again it seems good

**Comment by sivadevops1014** [comment]
> > check once again
> 
> yes, checked once again it seems good

few more code missing add forgot password field

**Comment by sivadevops1014** [comment]
added the feature you asked

**Review by medamshiva20 — APPROVED** [review]
Everything seems good

**Pull request merged**
