### PR TITLE
feature-3 developed

### PR DESCRIPTION
**Pull request by sivadevops1014**
feature-3 developed

### CODE REVIEW

**Comment by sivadevops1014** [comment]
once again check

**Comment by sivadevops1014** [comment]
> once again check

checked code is looking good

**Comment by sivadevops1014** [comment]
> > once again check
> 
> checked code is looking good

add login feature also that will be very good

**Comment by sivadevops1014** [comment]
login feature added as for your request

**Review by medamshiva20 — APPROVED** [review]
Approving feature-3

**Pull request merged**
